# 七牛云配置
shop.qiniu.resourcesUrl=http://img.wilderness-park.top/
shop.qiniu.accessKey=HUIYebXnTkYRAR-lEzbCzQMrmBFNF2-ORostN8TZ
shop.qiniu.secretKey=Xd62WoIGfCehrEVrZEx84eGWo18YwCFPUBVmnbzY
shop.qiniu.bucket=wildness-park
# 具体查看QiniuZone.java
shop.qiniu.zone=HUA_DONG 

shop.aLiDaYu.accessKeyId=
shop.aLiDaYu.accessKeySecret=
shop.aLiDaYu.signName=

shop.tokenAesKey=q5e6w6w9f4q497te

# \u672C\u5730\u6587\u4EF6\u4E0A\u4F20\u5B58\u50A8\u8DEF\u5F84
shop.imgUpload.imagePath=/opt/app/Wilderness-Park/mall4j/img/
# 1.\u672C\u5730\u6587\u4EF6\u4E0A\u4F20 2.\u4E03\u725B\u4E91 \u5982\u679C\u9009\u62E9\u4E86\u4E03\u725B\u4E91\u5C31\u4E0D\u9700\u8981\u518D\u914D\u7F6E\u672C\u5730\u6587\u4EF6\u4E0A\u4F20
shop.imgUpload.uploadType=1
# \u672C\u5730\u6587\u4EF6\u4E0A\u4F20\u7684\u8DEF\u5F84
shop.imgUpload.resourceUrl=http://localhost:8085/mall4j/img/